### ISSUE TITLE
Preview of document on Alfresco Process Services fails

### ISSUE THREAD

**Issue by VijayVelu-ClearCadence** [rjmfernandes/alfresco_http_activiti_client#1]
![ss-1](https://user-images.githubusercontent.com/28629388/28595021-bf61d090-71af-11e7-8f06-911348c0fe32.jpg)
Hi Rui,

I was exploring your add-on module for one of our customer's and was testing it out.
I noticed that when I trigger the my custom script through rules within ACS which calls the APS API to start the process, task gets assigned to the user, document information also is passed- but the raw content is not passed nor is the preview generated in the APS UI.

I checked the source code and noticed that the raw content is not passed to the APS, could this be the issue why the preview fails?

Could you please check and update? Thank you...

Good day...

Regards.

**Comment by chandrashekar319** [comment]
Hello, I have generated a AMP called http_js.amp and deployed in alfresco directory but i did not observe activiti and http root objects. can you please guide to that where it will reflect and any example.

**Comment by rjmfernandes** [comment]
this issue is already solved on last version.
regarding last comment the root variables are available on alfresco server side javascript api, suppose you dont have experience with it and suggest you to read the docs.alfresco.com over the topic

**Comment by chandrashekar319** [comment]
Thank you for your response and i want to set a rule using execute script to the folder with root objects(activiti & http) in afresco, is it correct way?

**Comment by rjmfernandes** [comment]
Yes. Installing the amp is installed as any other amp. And should show up as installed if you check /alfresco/s/enterprise/admin/admin-systemsummary if you check the modules installed (suppose you are using Alfresco Content Services Enterprise distribution) and the corresponding root variables should be able to use. Are you using the Alfresco Content Services Enterprise distribution? 

You can also use the JS Console https://github.com/share-extras/js-console for confirming access the root variables.

**Comment by chandrashekar319** [comment]
Yes, i am using Alfresco Content Services Enterprise and installed amp. As you said when i am developing script in js console getting "activiti" is not defined but as per project "activiti" & "http" root objects should come, right? Can you please share snippet code for above root objects.

**Comment by rjmfernandes** [comment]
not sure they should come, since js console does not know about them (not ootb), but they should work check example in project itself and try it out running the script https://github.com/rjmfernandes/alfresco_http_activiti_client/blob/master/startWorkflowExample.js
